version: '3.8'
services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shutterfly
  app:
    image: book-api:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
